name: CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - run: npm ci

      - run: npx nx affected -t lint --base=${{ github.event.before }} --head=${{ github.sha }} --parallel=3
      - run: npx nx affected -t typecheck --base=${{ github.event.before }} --head=${{ github.sha }} --parallel=3
      - run: npx nx affected -t test --base=${{ github.event.before }} --head=${{ github.sha }} --parallel=3
      - run: npx nx affected -t test:container --base=${{ github.event.before }} --head=${{ github.sha }} --parallel=3
      - run: npx nx affected -t build --base=${{ github.event.before }} --head=${{ github.sha }} --parallel=3
